"""Add AgentRun and AgentEvaluation tables

Revision ID: 3418f9e69834
Revises: 1a31ce608336
Create Date: 2025-10-05 13:10:47.345453

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3418f9e69834'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default=sa.text("'pending'")),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentrun_created_at'), 'agentrun', ['created_at'], unique=False)
    op.create_index(op.f('ix_agentrun_status'), 'agentrun', ['status'], unique=False)
    op.create_index(op.f('ix_agentrun_trace_id'), 'agentrun', ['trace_id'], unique=False)
    op.create_index(op.f('ix_agentrun_user_id'), 'agentrun', ['user_id'], unique=False)
    op.create_table('agentevaluation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('eval_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['run_id'], ['agentrun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentevaluation_created_at'), 'agentevaluation', ['created_at'], unique=False)
    op.create_index(op.f('ix_agentevaluation_metric_name'), 'agentevaluation', ['metric_name'], unique=False)
    op.create_index(op.f('ix_agentevaluation_run_id'), 'agentevaluation', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agentevaluation_run_id'), table_name='agentevaluation')
    op.drop_index(op.f('ix_agentevaluation_metric_name'), table_name='agentevaluation')
    op.drop_index(op.f('ix_agentevaluation_created_at'), table_name='agentevaluation')
    op.drop_table('agentevaluation')
    op.drop_index(op.f('ix_agentrun_user_id'), table_name='agentrun')
    op.drop_index(op.f('ix_agentrun_trace_id'), table_name='agentrun')
    op.drop_index(op.f('ix_agentrun_status'), table_name='agentrun')
    op.drop_index(op.f('ix_agentrun_created_at'), table_name='agentrun')
    op.drop_table('agentrun')
    # ### end Alembic commands ###
