"""Add thread_id column to AgentRun table

Revision ID: 97e72db5cb77
Revises: 3418f9e69834
Create Date: 2025-10-06 13:04:29.787772

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97e72db5cb77'
down_revision = '3418f9e69834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: LangGraph checkpoint tables (checkpoints, checkpoint_blobs, checkpoint_writes, checkpoint_migrations)
    # are managed by LangGraph and should not be modified by Alembic
    op.add_column('agentrun', sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_agentrun_thread_id'), 'agentrun', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agentrun_thread_id'), table_name='agentrun')
    op.drop_column('agentrun', 'thread_id')
    # ### end Alembic commands ###
